[2022-12-31T20:36:51.149+0700] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tutorial.sleep manual__2022-12-31T13:03:43.883841+00:00 [queued]>
[2022-12-31T20:36:51.159+0700] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tutorial.sleep manual__2022-12-31T13:03:43.883841+00:00 [queued]>
[2022-12-31T20:36:51.159+0700] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T20:36:51.159+0700] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2022-12-31T20:36:51.159+0700] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T20:36:51.174+0700] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): sleep> on 2022-12-31 13:03:43.883841+00:00
[2022-12-31T20:36:51.177+0700] {standard_task_runner.py:55} INFO - Started process 155376 to run task
[2022-12-31T20:36:51.180+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'sleep', 'manual__2022-12-31T13:03:43.883841+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/tmp/tmpyuqwi6bu']
[2022-12-31T20:36:51.181+0700] {standard_task_runner.py:83} INFO - Job 16: Subtask sleep
[2022-12-31T20:36:51.229+0700] {task_command.py:389} INFO - Running <TaskInstance: tutorial.sleep manual__2022-12-31T13:03:43.883841+00:00 [running]> on host daominhkhanh
[2022-12-31T20:36:51.285+0700] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2022-12-31T13:03:43.883841+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-31T13:03:43.883841+00:00
[2022-12-31T20:36:51.286+0700] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-31T20:36:51.287+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2022-12-31T20:36:51.294+0700] {subprocess.py:86} INFO - Output:
[2022-12-31T20:36:54.327+0700] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 155376. PIDs of all processes in the group: [155377, 155376]
[2022-12-31T20:36:54.327+0700] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 155376
[2022-12-31T20:36:54.327+0700] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-31T20:36:54.328+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-31T20:36:54.335+0700] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    result = self.subprocess_hook.run_command(
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-31T20:36:54.349+0700] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=sleep, execution_date=20221231T130343, start_date=20221231T133651, end_date=20221231T133654
[2022-12-31T20:36:54.369+0700] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task sleep (Task received SIGTERM signal; 155376)
[2022-12-31T20:36:54.379+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=155377, status='terminated', started='20:36:50') (155377) terminated with exit code None
[2022-12-31T20:36:54.380+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=155376, status='terminated', exitcode=1, started='20:36:50') (155376) terminated with exit code 1
